# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: BTrace CI/CD

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build BTrace
        run: ./gradlew -x test build
      - name: Upload build data
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            btrace-dist/build
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 20]
    steps:
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Download build data
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Run tests
        run: ./gradlew test