# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: BTrace Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Import GPG Key
      run: |
        echo "${GPG_PRIVATE_KEY}" > /tmp/secret.gpg
      shell: bash
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Store JAVA_8_HOME
      run: JAVA_PATH=$(which java) && echo "JAVA_8_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      shell: bash
    - name: Set up Java 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Store JAVA_9_HOME
      run: JAVA_PATH=$(which java) && echo "JAVA_9_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      shell: bash
    - name: Set up Java 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Store JAVA_15_HOME
      run: JAVA_PATH=$(which java) && echo "JAVA_15_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      shell: bash
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Store JAVA_11_HOME
      run: JAVA_PATH=$(which java) && echo "JAVA_11_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      shell: bash
    - name: Checkout
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: JAVA_HOME="$JAVA_15_HOME" ./gradlew build -x test
    - name: Run Tests
      run: JAVA_HOME="$JAVA_11_HOME" ./run_tests.sh
    - name: Deploy Maven Snapshots
      if: github.ref == 'refs/heads/develop'
      run: ./gradlew :btrace-dist:publish
      env:
        ORG_GRADLE_PROJECT_signing.secretKeyRingFile: /tmp/secret.gpg
        ORG_GRADLE_PROJECT_signing.keyId: ${{ secrets.GPG_KEY_ID }}
        ORG_GRADLE_PROJECT_signing.password: ${{ secrets.GPG_PASSPHRASE }}
        BTRACE_SONATYPE_USER: ${{ secrets.BTRACE_SONATYPE_USER }}
        BTRACE_SONATYPE_PWD: ${{ secrets.BTRACE_SONATYPE_PWD }}
    - name: Archive binary artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binary-dist
        path: |
          btrace-dist/build/distributions/**/btrace-*-bin*.tar.gz
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          btrace-instr/build/reports/**/*

