on:
  push:
    tags:
      - 'v*'

name: Create Release

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Store JAVA_8_HOME
        run: JAVA_PATH=$(which java) && echo "JAVA_8_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      - name: Set up Java 9
        uses: actions/setup-java@v1
        with:
          java-version: 9
      - name: Store JAVA_9_HOME
        run: JAVA_PATH=$(which java) && echo "JAVA_9_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      - name: Set up Java 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Store JAVA_16_HOME
        run: JAVA_PATH=$(which java) && echo "JAVA_16_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Store JAVA_11_HOME
        run: JAVA_PATH=$(which java) && echo "JAVA_11_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      - name: Build artifacts
        run: JAVA_HOME="$JAVA_11_HOME" ./gradlew :btrace-dist:build
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          files: |
            btrace-dist/build/distributions/btrace-${{ github.ref }}-bin.tar.gz
            btrace-dist/build/distributions/btrace-${{ github.ref }}-bin.zip
            btrace-dist/build/distributions/btrace-${{ github.ref }}-sdkman-bin.zip